[meta]
version = "0.1.0"

[project]
name = "bumpercare"
package = "bumpercare"
main_lang = "py"
version = "0.0.9"
version_date = "2018-03-02"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2017"
description = "BumperWare server"
dev_status = "planning"
license = "mit"
relpath = "py/bumpercare"
state = "shared"
url = "https://jddixon.github.io/bumpercare"

[python]
test_dir = "tests"
packages = [ "bumpercare",]
package_dir = [ "src",]
py_modules = []
scripts = []
ext_modules = []
distshare = [ "rnglib",]
requirements = [ "setuptools",]
test_requirements = []
